media: 
  input: static/images
  output: /images
content:
  - name: publicaties
    label: Publicaties (standaard)
    type: collection
    path: 'content/publicaties-standaard'
    view:
      fields: [ date, draft, title ]
    fields:
      - name: date
        label: Date
        type: date
      - name: draft
        label: Draft
        type: boolean
      - name: title
        label: Title
        type: string
      - name: auteur
        label: Auteur
        type: string
      - name: genre
        label: Genre
        type: string
      - name: reeks
        label: Reeks
        type: string
      - name: body
        label: Body
        type: rich-text
  - name: publicaties-htmld
    label: Publicaties (htmld)
    type: collection
    path: 'content/publicaties-htmld'
    view:
      fields: [ date, draft, title ]
    fields:
      - name: date
        label: Date
        type: date
      - name: draft
        label: Draft
        type: boolean
      - name: title
        label: Title
        type: string
      - name: auteur
        label: Auteur
        type: string
      - name: genre
        label: Genre
        type: genre
      - name: reeks
        label: Reeks
        type: string
      - name: body
        label: Body
        type: text
  - name: config
    label: Hugo config
    path: hugo.yaml
    type: file
    fields:
      - name: baseURL
        label: baseURL
        type: string
        pattern: ^(https?:\/\/)?(www\.)?[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}(\/[^\s]*)?$
      - name: languageCode
        label: Language Code
        type: string
      - name: title
        label: Website Title
        type: string
      - name: theme
        label: Website Theme
        type: string